backend:
  name: github
  repo: whatisdis/patternfly-next
media_folder: static/assets/images
publish_mode: editorial_workflow
display_url: https://patternfly-cms.netlify.com
base:
  fields: &ref_0
    - label: Template Key
      name: templateKey
      widget: hidden
      default: about-page
    - label: Body
      name: body
      widget: markdown
collections:
  - name: pages
    label: Pages
    files:
      - file: src/site/pages/accessibility-guide.md
        label: Accessibility
        name: accessibility
        fields: *ref_0
      - file: src/site/pages/contribution.md
        label: Contribution
        name: contribution
        fields: *ref_0
      - file: src/site/pages/getting-started.md
        label: Getting Started
        name: getting-started
        fields: *ref_0
      - file: src/site/pages/guidelines.md
        label: Guidelines
        name: guidelines
        fields: *ref_0
  - name: components
    label: Components
    files:
      - file: src/patternfly/components/Alert/docs/code.md
        label: Alert
        name: alert
        fields: *ref_0
      - file: src/patternfly/components/Backdrop/docs/code.md
        label: Backdrop
        name: backdrop
        fields: *ref_0
      - file: src/patternfly/components/BackgroundImage/docs/code.md
        label: BackgroundImage
        name: BackgroundImage
        fields: *ref_0
      - file: src/patternfly/components/Badge/docs/code.md
        label: Badge
        name: Badge
        fields: *ref_0
      - file: src/patternfly/components/Box/docs/code.md
        label: Box
        name: box
        fields: *ref_0
      - file: src/patternfly/components/MyComponent/docs/code.md
        label: MyComponent
        name: MyComponent
        fields: *ref_0
      - file: src/patternfly/components/MyComponent2/docs/code.md
        label: MyComponent2
        name: MyComponent2
        fields: *ref_0
