backend:
  name: github
  repo: whatisdis/patternfly-next
media_folder: static/assets/images
public_folder: /img
base: &base
  fields:
    - label: Template Key
      name: templateKey
      widget: hidden
      default: about-page
    - label: Body
      name: body
      widget: markdown
collections:
  - name: pages
    label: Pages
    files:
      - file: src/site/pages/accessibility-guide.md
        label: Accessibility
        name: accessibility
        <<: *base
      - file: src/site/pages/contribution.md
        label: Contribution
        name: contribution
        <<: *base
  - name: components
    label: Components
    files:
      - file: src/patternfly/components/Alert/docs/code.md
        label: Alert
        name: alert
        <<: *base
      - file: src/patternfly/components/Backdrop/docs/code.md
        label: Backdrop
        name: backdrop
        <<: *base
      - file: src/patternfly/components/Box/docs/code.md
        label: Box
        name: box
        <<: *base
